env:
  initial_pos_z_offset: 0.1

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: StaticTraversableScene
  scene_model: Pablo
  trav_map_resolution: 0.1
  trav_map_erosion: 2
  trav_map_with_objects: true
  build_graph: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  floor_plane_visible: false

robots:
  - type: Turtlebot
    obs_modalities: [scan, rgb, depth]
    scale: 1.0
    self_collision: false
    action_normalize: true
    action_type: continuous
    controller_config:
      base:
        name: DifferentialDriveController

objects: []

task:
  type: PointNavigationTask
  robot_idn: 0
  floor: 0
  initial_pos: null
  initial_quat: null
  goal_pos: null
  goal_tolerance: 0.36    # turtlebot bodywidth
  goal_in_polar: false
  path_range: [1.0, 10.0]
  visualize_goal: true
  visualize_path: true
  n_vis_waypoints: 25
  reward_type: geodesic
  termination_config:
    max_collisions: 500
    max_steps: 500
    fall_height: 0.03
  reward_config:
    r_potential: 1.0
    r_collision: 0.1
    r_pointgoal: 10.0
