basic_settings:
  site_title: BEHAVIOR
  favicon_image: /assets/img/behavior/behicon.png

header_settings:
  logo_image: /assets/img/behavior/b02.png
  mobile_logo_image: /assets/img/behavior/b02.png
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landingb

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /
    - title: 'About BEHAVIOR'
      submenu_items:
      - title: 'Benchmark Setup'
        url: /benchmark-guide
        icon: ni-settings-gear-65 text-default
      - title: 'List of Activities'
        url: /behavior-gallery/activity.html
        icon: ni-bullet-list-67 text-success
      - title: 'Create your own activity'
        url: /activity-annotation
        icon: ni-atom text-primary
      - title: 'Dataset of VR Demos'
        url: /vr-demos
        icon: ni-glasses-2 text-info
    - title: 'Code'
      submenu_items:
      - title: 'Installation Instructions'
        url: https://stanfordvl.github.io/behavior/installation.html
        icon: ni-single-copy-04 text-default
      - title: 'BEHAVIOR'
        url: https://github.com/StanfordVL/behavior
        icon: ni-bullet-list-67 text-success
      - title: 'iGibson'
        url: https://github.com/StanfordVL/iGibson
        icon: ni-books text-primary
      - title: 'BDDL'
        url: https://github.com/StanfordVL/bddl
        icon: ni-chart-bar-32 text-info
    - title: 'Documentation'
      submenu_items:
      - title: 'BEHAVIOR'
        url: https://stanfordvl.github.io/behavior/intro.html
        icon: ni-bullet-list-67 text-success
      - title: 'iGibson'
        url: http://svl.stanford.edu/igibson/docs/
        icon: ni-books text-primary
      - title: 'BDDL'
        url: https://github.com/StanfordVL/bddl/blob/master/README.md
        icon: ni-chart-bar-32 text-info
    - title: 'Workshops'
      submenu_items:
      - title: ICCV21
        url: /iccv21
        icon: ni-spaceship text-primary

footer_settings:
  footer_tagline: BEHAVIOR has been developed by the Stanford Vision and Learning Lab and collaborators.

# contact_settings:
#   form_action: 'https://formspree.io/hello@jekyllthemes.io'
#   confirmation_url: '/thanks'
#   email_subject: 'Contact form submission'
#   send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://twitter.com/jekyllthemesio'
  reddit_url: ''
  linkedin_url: ''

# authors:
#   tom:
#     name: Tom
#     picture: /assets/img/faces/team-1.jpg
#   jane:
#     name: Jane
#     picture: /assets/img/faces/team-4.jpg
#   michael:
#     name: Michael
#     picture: /assets/img/faces/michael.jpg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 
