basic_settings:
  site_title: BEHAVIOR
  favicon_image: /assets/img/behavior/behicon.png

header_settings:
  logo_image: /assets/img/behavior/b02.png
  mobile_logo_image: /assets/img/behavior/b02.png
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landingb

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /
    - title: 'Benchmark Guide'
      url: https://docs.google.com/document/d/1u2m9Ld6Qo3eG-fvCzuAZN6lHxwpVVBlwLVdzo_WDlNI/edit?usp=sharing
    - title: 'Code'
      submenu_items:
      - title: 'Installation Instructions'
        url: https://docs.google.com/document/d/1u2m9Ld6Qo3eG-fvCzuAZN6lHxwpVVBlwLVdzo_WDlNI/edit#heading=h.mpuld4k8chhh
      - title: 'BEHAVIOR Starter code'
        url: https://github.com/StanfordVL/BehaviorChallenge2021
      - title: 'BEHAVIOR Baselines'
        url: https://github.com/StanfordVL/behavior-baselines
      - title: 'BDDL'
        url: https://github.com/StanfordVL/bddl
      - title: 'iGibson'
        url: https://github.com/StanfordVL/iGibson
    - title: 'List of Activities'
      url: /activity_list.html
    - title: 'Create your own activity'
      url: https://StanfordVL.github.io/behavior-activity-annotation/
      # submenu_items:
      # - title: Landing Page
      #   url: /
      #   icon: ni-spaceship text-success    
      # - title: Blog
      #   url: /blog
      #   icon: ni-books text-primary
    # - title: 'Features'
    #   url: /features     
    # - title: Pricing
    #   url: /pricing        
    # - title: 'Blog'
    #   submenu_items:
    #   - title: Blog
    #     url: /blog
    #     icon: ni-books text-primary
    #   - title: Narrow Grid Example
    #     url: /blog-narrow-example
    #     icon: ni-align-center text-success
    #   - title: Wide Grid Example
    #     url: /blog-grid-example
    #     icon: ni-image text-info
    #   - title: List Example
    #     url: /blog-list-example
    #     icon: ni-bullet-list-67 text-default    
    # - title: 'About'
    #   url: '/about'
    # - title: 'Contact'
    #   url: '/contact'
    - title: 'Workshops'
      url: /iccv21
      icon: fa-wrench text-default
      submenu_items:
      - title: ICCV21
        url: /iccv21

footer_settings:
  footer_tagline: BEHAVIOR has been developed by the Stanford Vision and Learning Lab and collaborators.

# contact_settings:
#   form_action: 'https://formspree.io/hello@jekyllthemes.io'
#   confirmation_url: '/thanks'
#   email_subject: 'Contact form submission'
#   send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://twitter.com/jekyllthemesio'
  reddit_url: ''
  linkedin_url: ''

# authors:
#   tom:
#     name: Tom
#     picture: /assets/img/faces/team-1.jpg
#   jane:
#     name: Jane
#     picture: /assets/img/faces/team-4.jpg
#   michael:
#     name: Michael
#     picture: /assets/img/faces/michael.jpg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 
