# Generated by Django 4.2 on 2023-04-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Synset",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("is_substance", models.BooleanField(default=False)),
                ("legal", models.BooleanField(default=False)),
                ("children", models.ManyToManyField(blank=True, to="data.synset")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("room_requirements", models.CharField(max_length=300)),
                ("synsets", models.ManyToManyField(to="data.synset")),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("ready", models.BooleanField(default=False)),
                ("room_config", models.CharField(max_length=1000)),
            ],
            options={
                "unique_together": {("name", "ready")},
            },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("ready", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.category"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="synset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data.synset"
            ),
        ),
    ]
