# Generated by Django 4.2 on 2023-04-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="planned",
            field=models.BooleanField(default=True),
        ),
    ]
