# Generated by Django 4.1.8 on 2023-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_object_planned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="synset",
            name="parents",
        ),
        migrations.AlterField(
            model_name="synset",
            name="children",
            field=models.ManyToManyField(
                blank=True, related_name="parents_set", to="data.synset"
            ),
        ),
    ]
