# Generated by Django 4.1.8 on 2023-04-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_remove_synset_parents_alter_synset_children"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="synset",
            name="children",
        ),
        migrations.AddField(
            model_name="synset",
            name="ancestors",
            field=models.ManyToManyField(
                blank=True, related_name="descendants", to="data.synset"
            ),
        ),
        migrations.AddField(
            model_name="synset",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="data.synset"
            ),
        ),
    ]
