# Generated by Django 4.1.8 on 2023-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_remove_synset_children_synset_ancestors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="synset",
            name="state",
            field=models.CharField(default="light", max_length=64),
        ),
    ]
