basic_settings:
  site_title: BEHAVIOR
  favicon_image: /assets/img/behavior/behicon.png

header_settings:
  logo_image: /assets/img/behavior/b02.png
  mobile_logo_image: /assets/img/behavior/b02.png
  # Choose a color for your header [blue, dark, light].
  theme: light
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landingb

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /

    - title: 'BEHAVIOR-1K'
      url: /behavior-1k
      submenu_items:
      - title: 'Overview'
        url: /behavior-1k
        icon: ni-bullet-list-67 text-default
      - title: 'Demo Colab'
        url: https://bit.ly/b1k-colab
        icon: ni-laptop text-warning
      - title: 'Knowledgebase'
        url: /knowledgebase
        icon: ni-atom text-info
      - title: 'Getting Started'
        url: /omnigibson/getting_started/installation.html
        icon: ni-spaceship text-success
      - title: 'OmniGibson'
        url: https://github.com/StanfordVL/OmniGibson
        icon: ni-single-copy-04 text-danger
      - title: 'BDDL'
        url: https://github.com/StanfordVL/bddl
        icon: ni-chart-bar-32 text-warning
      - title: 'Asset Sources'
        url: /asset-sources
        icon: ni-shop text-info

    - title: 'BEHAVIOR-100'
      url: /behavior-100
      submenu_items:
      - title: 'Overview'
        url: /behavior-100
        icon: ni-bullet-list-67 text-default
      # - title: 'Benchmark Setup'
      #   url: /benchmark-guide
      #   icon: ni-settings-gear-65 text-default
      # - title: 'Installation Instructions'
      #   url: https://stanfordvl.github.io/behavior/installation.html
      #   icon: ni-single-copy-04 text-default
      - title: 'Main Codebase'
        url: https://github.com/StanfordVL/behavior
        icon: ni-single-copy-04 text-success
      - title: 'BDDL'
        url: https://github.com/StanfordVL/bddl
        icon: ni-chart-bar-32 text-info
      - title: 'iGibson'
        url: https://github.com/StanfordVL/iGibson
        icon: ni-books text-danger
      - title: 'Dataset of VR Demos'
        url: /vr-demos
        icon: ni-glasses-2 text-info
      - title: 'VR Demo Video Gallery'
        url: /behavior-gallery/activity.html
        icon: ni-bullet-list-67 text-warning
      # - title: 'BEHAVIOR-100 Doc'
      #   url: https://stanfordvl.github.io/behavior/intro.html
      #   icon: ni-bullet-list-67 text-success
      # - title: 'iGibson Doc'
      #   url: http://svl.stanford.edu/igibson/docs/
      #   icon: ni-books text-primary
    # - title: 'Shared'
    #     - title: 'Create your own activity'
    #     url: /activity-creation
    #     icon: ni-atom text-primary
    
    - title: 'Workshops'
      submenu_items:
      - title: ICCV21
        url: /iccv21
        icon: ni-spaceship text-primary
      - title: ECCV22
        url: /eccv22
        icon: ni-spaceship text-primary

    - title: 'Research'
      submenu_items:
      - title: 'Publications'
        url: /research
        icon: ni-books text-success
      - title: 'BEHAVIOR Vision Suite'
        url: "https://behavior-vision-suite.github.io/"
        icon: ni-camera-compact text-primary

footer_settings:
  footer_tagline: BEHAVIOR has been developed by the Stanford Vision and Learning Lab and collaborators.

# Team info on the main page. Note that the pictures are relative links to the assets/img/people folder.
# This way we ensure that you will not put any remote URLs which tend to break.
team_info:
  - title: "The BEHAVIOR-1K Team"
    members:
      - name: "Chengshu (Eric) Li"
        picture: "chengshu.jpg"
        url: "http://chengshuli.me"
      - name: "Ruohan Zhang"
        picture: "ruohan_zhang_photo.jpeg"
        url: "https://ai.stanford.edu/~zharu/"
      - name: "Josiah Wong"
        picture: "josiah_wong.jpg"
        url: "http://jowo.me"
      - name: "Cem Gokmen"
        picture: "cemgokmen.jpg"
        url: "https://www.cemgokmen.com/"
      - name: "Sanjana Srivastava"
        picture: "sanjana.jpg"
        url: "https://www.linkedin.com/in/sanjana-srivastava5/"
      - name: "Hang Yin"
        picture: "hang_yin.png"
        url: "https://hang-yin.github.io/portfolio/"
      - name: "Wensi Ai"
        picture: "wensi_ai.jpg"
        url: "http://wensi-ai.github.io/"
      - name: "Sujay Garlanka"
        picture: "sujay_garlanka.jpeg"
        url: "https://sujaygarlanka.com/"
      - name: "Benjamin Martinez"
        picture: "benjamin_martinez.png"
        url: "https://web.stanford.edu/~benjm/"
      - name: "Roberto Martín-Martín"
        picture: "roberto_martinmartin.jpg"
        url: "https://robertomartinmartin.com/"
      - name: "Silvio Savarese"
        picture: "silvio_savarese.jpg"
        url: "http://cvgl.stanford.edu/silvio/"
      - name: "Hyowon Gweon"
        picture: "hyowon_gweon.jpg"
        url: "https://web.stanford.edu/~hyo/Home.html"
      - name: "Karen Liu"
        picture: "Karen.png"
        url: "https://ckllab.stanford.edu/c-karen-liu"
      - name: "Jiajun Wu"
        picture: "jiajun_wu.jpg"
        url: "https://jiajunwu.com/"
      - name: "Li Fei-Fei"
        picture: "li_fei_fei.jpg"
        url: "https://engineering.stanford.edu/people/fei-fei-li"
  - title: "Alumni"
    members:
      - name: "Chen Wang"
        picture: "chen_wang.jpeg"
        url: "https://www.chenwangjeremy.net/"
      - name: "Gabrael Levine"
        picture: "gabrael.jpg"
        url: "https://www.gabrael.io/"
      - name: "Michael Lingelbach"
        picture: "michael_lingelbach.jpg"
        url: "https://github.com/mjlbach/"
      - name: "Ayano Hiranaka"
        picture: "ayano_hiranaka.jpg"
        url: "https://misoshiruseijin.github.io/"
      - name: "Minjune Hwang"
        picture: "minjune.jpg"
        url: "https://mj-hwang.github.io/"
      - name: "Jiankai Sun"
        picture: "jiankai.jpg"
        url: "http://web.stanford.edu/~jksun/"
      - name: "Mona Anvari"
        picture: "mona.jpg"
        url: "https://monaanvari.github.io/portfolio/"
      - name: "Arman Aydin"
        picture: "arman.jpg"
        url: "https://www.linkedin.com/in/arman-aydin-915035185/?trk=public_profile_like_view_actor-name"
      - name: "Emily Jin"
        picture: "emily_jin.png"
        url: "http://emilyjin.me/"
      - name: "Manasi Sharma"
        picture: "manasi.jpg"
        url: "https://github.com/manasi-sharma"
      - name: "Dhruva Bansal"
        picture: "dhruva.jpg"
        url: "https://dhruvabansal.com/"
      - name: "Samuel Hunter"
        picture: "samuel.jpg"
        url: "#"
      - name: "Kyu-Young Kim"
        picture: "kyuyoung.jpg"
        url: "https://kykim0.github.io/"
      - name: "Alan Lou"
        picture: "alan_lou.jpg"
        url: "https://icme.stanford.edu/people/alan-lou"
      - name: "Caleb Matthews"
        picture: "caleb_matthews.jpg"
        url: "https://www.linkedin.com/in/caleb-matthews/"
      - name: "Ivan Villa-Renteria"
        picture: "ivan_villa_renteria.jpg"
        url: "https://www.linkedin.com/in/ivillare/"
      - name: "Jerry Tang"
        picture: "jerry_tang.jpg"
        url: "https://www.linkedin.com/in/jerry-tang-b37026162/"
      - name: "Claire Tang"
        picture: "claire_tang.png"
        url: "#"
      - name: "Fei Xia"
        picture: "fei_xia.png"
        url: "https://fxia22.github.io"
      - name: "Kent Vainio"
        picture: "kent_vainio.jpg"
        url: "https://www.linkedin.com/in/kent-vainio-4749b0145/?originalSubdomain=ch"
      - name: "Zheng Lian"
        picture: "zheng_lian.jpg"
        url: "https://profiles.stanford.edu/zheng-lian"
      - name: "Shyamal Buch"
        picture: "shyamal.jpg"
        url: "https://cs.stanford.edu/~shyamal"
      - name: "Yunzhu Li"
        picture: "yunzhu.jpeg"
        url: "https://yunzhuli.github.io/"


# contact_settings:
#   form_action: 'https://formspree.io/hello@jekyllthemes.io'
#   confirmation_url: '/thanks'
#   email_subject: 'Contact form submission'
#   send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://github.com/StanfordVL/behavior'
  reddit_url: ''
  linkedin_url: ''

# authors:
#   svl:
#     name: SVL
#     picture: /assets/img/svl_logo2.png
#   jane:
#     name: Jane
#     picture: /assets/img/faces/team-4.jpg
#   michael:
#     name: Michael
#     picture: /assets/img/faces/michael.jpg

advanced_settings:
  analytics_code: |
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-6L1G6GMR63"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6L1G6GMR63');
    </script>
  header_js: 
  footer_js: 
