name: Build and deploy BEHAVIOR website

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-omnigibson-docs:
    runs-on: [linux, gpu-enabled]
    container:
      image: stanfordvl/omnigibson-dev:latest
      options: --gpus=all --privileged --user=root
      env:
        DISPLAY: ""
        OMNIGIBSON_HEADLESS: 1
      volumes:
        - /scr/omni-data/datasets:/data
        - /usr/share/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json
        - /usr/share/vulkan/icd.d/nvidia_layers.json:/etc/vulkan/implicit_layer.d/nvidia_layers.json
        - /usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json
        - /scr/omni-data/isaac-sim/cache/ov:/root/.cache/ov:rw
        - /scr/omni-data/isaac-sim/cache/pip:/root/.cache/pip:rw
        - /scr/omni-data/isaac-sim/cache/glcache:/root/.cache/nvidia/GLCache:rw
        - /scr/omni-data/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw
        - /scr/omni-data/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw
        - /scr/omni-data/isaac-sim/config:/root/.nvidia-omniverse/config:rw
        - /scr/omni-data/isaac-sim/data:/root/.local/share/ov/data:rw
        - /scr/omni-data/isaac-sim/documents:/root/Documents:rw

    defaults:
      run:
        shell: micromamba run -n omnigibson /bin/bash -leo pipefail {0}

    steps:
      - name: Fix home
        run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
          path: omnigibson-src

      - name: Install
        working-directory: omnigibson-src
        run: pip install -e .

      - name: Install dev requirements
        working-directory: omnigibson-src
        run: pip install -r requirements-dev.txt

      - name: Build docs
        working-directory: omnigibson-src
        run: source scripts/build_docs.sh

      - name: Copy benchmark index page
        working-directory: omnigibson-src
        run: mkdir site/benchmark && cp scripts/benchmark* site/benchmark/ && cd site/benchmark && mv benchmark.html index.html

      - name: Fetch benchmark file from gh-pages branch
        working-directory: omnigibson-src
        run: |
          git fetch origin gh-pages:gh-pages --force
          git show gh-pages:benchmark/data.js > ./site/benchmark/data.js
          git diff
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./omnigibson-src/site
