name: Update Integration

on:
  schedule: # runs at 6am PST every day
    - cron: "0 13 * * *" 
  push: # runs on push to main
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Fetch bddl data
      - name: Clone B100 BDDL Repo
        uses: actions/checkout@v3
        with:
          repository: StanfordVL/bddl
          path: bddl 
      - name: Clone B1K BDDL Repo
        uses: actions/checkout@v3
        with:
          repository: StanfordVL/ObjectPropertyAnnotation
          path: ./ObjectPropertyAnnotation
          token: ${{ secrets.REPO_TOKEN }}

      # Fetch ig pipeline data
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Clone ig pipeline Repo
        uses: actions/checkout@v3
        with:
          repository: StanfordVL/ig_pipeline
          path: ig_pipeline
          token: ${{ secrets.REPO_TOKEN }}
      - name: Install dvc
        run: pip install dvc[gs]
      - name: Authenticate on Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Pull dvc data
        working-directory: ig_pipeline
        run: dvc pull combined_room_object_list combined_room_object_list_future object_inventory object_inventory_future

      # Build static content
      - name: Checkout integration repo
        uses: actions/checkout@v3
        with:
          path: b1k-integration
      - name: Install dependencies
        working-directory: b1k-integration
        run: pip install -r requirements.txt
      - name: Build integration
        working-directory: b1k-integration
        run: python server.py
      
      # Deploy to github pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: b1k-integration/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

